[tool.poetry]
name = "ideadensity"
version = "0.6.0"
description = "Python library for computing propositional idea density"
authors = ["Jason Robison <jrrobison@protonmail.com>"]
readme = "README.md"
license = "GNU GPLv2"
homepage = "https://github.com/jrrobison1/ideadensity"
repository = "https://github.com/jrrobison1/ideadensity"
keywords = ["nlp", "idea density", "linguistics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
packages = [{ include = "ideadensity" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
levenshtein = ">=0.25"
pyqt6 = { version = "^6.6.1", optional = true }
spacy = "^3.8.4"
tomli = { version = "^2.2.1", python = "<3.11" }

[tool.poetry.extras]
gui = ["pyqt6"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
